[session]
projects = [
  "$DEVSPACE/code/projects/*",
  "$DEVSPACE/code/experiments/*",
  "$DEVSPACE/code/archived/*",
  "$DEVSPACE/images/*",
  "$DEVSPACE/infra/*",
  "$DEVSPACE/repos/*",
  "$DEVSPACE/work",
]
ignore_dir = [ "~/downloads", "~/Downloads" ]

[lsp.jdtls.maven]
globalSettings = "~/.m2/settings.xml"

[[lsp.jdtls.runtimes]]
name = "JavaSE-1.8"
path = "/etc/jdk/zulu8"

[[lsp.jdtls.runtimes]]
name = "JavaSE-21"
path = "/etc/jdk/zulu21"
default = true

[[lsp.jdtls.runtimes]]
name = "JavaSE-25"
path = "/etc/jdk/zulu25"
